#!/usr/bin/env ruby
#--
# Gloves Keyboard Library
#
# Copyright (C) 2011 Novell, Inc.
#   This library is free software; you can redistribute it and/or modify
# it only under the terms of version 2.1 or version 3 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
#   You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#++

$LOAD_PATH.unshift File.join(File.dirname(__FILE__),"..","lib")
require "glove/keyboard"
begin
  args = {}

  if ARGV.empty?
    keyboard = Glove::Keyboard::read(args)
    puts keyboard.inspect unless keyboard.nil?
    if keyboard.nil?
      error	= Glove::Keyboard::last_error
      puts "returned error: #{error}" if error
    end
  else
    puts Glove::Keyboard::modify({}, {"keymap"=>ARGV[0]})
  end
rescue Exception => e
  puts e.inspect
  raise
end
