#--
# Config Agents Framework
#
# Copyright (C) 2011 Novell, Inc. 
#   This library is free software; you can redistribute it and/or modify
# it only under the terms of version 2.1 or version 3 of the GNU Lesser General Public
# License as published by the Free Software Foundation. 
#
#   This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more 
# details. 
#
#   You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software 
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#++

require "rake"
require "packaging"

desc "install all things on system"
task :install, :prefix, :ruby_path do |t,args|
  args.with_defaults :prefix => '/',:ruby_path => Dir["/usr/lib*/ruby/vendor_ruby/1.*/"][0]
  sh "mkdir -p #{args[:prefix]}#{args[:ruby_path]}/dbus_clients"
  sh "mkdir -p #{args[:prefix]}#{args[:ruby_path]}/config_agent_service"
  sh "cp dbus_clients/* #{args[:prefix]}#{args[:ruby_path]}/dbus_clients"
  sh "cp config_agent_service/* #{args[:prefix]}#{args[:ruby_path]}/config_agent_service"
  sh "mkdir -p #{args[:prefix]}usr/lib/config-agent-generator"
  sh "cp agent-generator/* #{args[:prefix]}usr/lib/config-agent-generator/"
  sh "mkdir -p #{args[:prefix]}usr/bin/"
  sh "ln -s /usr/lib/config-agent-generator/agent-generator #{args[:prefix]}usr/bin/config-agent-generator" unless File.exists?("#{args[:prefix]}usr/bin/config-agent-generator")
  sh "mkdir -p #{args[:prefix]}/usr/share/config_agents/"
  sh "mkdir -p #{args[:prefix]}/usr/share/config_agents/bin"
  sh "cp dbus_service/service_binary/* #{args[:prefix]}/usr/share/config_agents/bin"
  sh "chmod +x #{args[:prefix]}/usr/share/config_agents/bin/*"
  sh "mkdir -p #{args[:prefix]}etc/dbus-1/system.d/"
  sh "cp -r dbus_service/dbus-policies/* #{args[:prefix]}etc/dbus-1/system.d/"
  sh "mkdir -p #{args[:prefix]}usr/share/dbus-1/system-services/"
  sh "cp -r dbus_service/dbus-services/* #{args[:prefix]}usr/share/dbus-1/system-services/"
  sh "mkdir -p #{args[:prefix]}/var/log/config_agents"
end

Packaging::Configuration.run do |conf|
  conf.obs_project = "YaST:Head:YaST++"
  conf.obs_target = "devel_languages_ruby_extensions_openSUSE_Factory"
end

task :generate_spec do
  sh "sed 's/VERSION_TEMPLATE/#{Packaging::Configuration.instance.version}/g' libconfigagent.spec.template > package/libconfigagent.spec"
end

#add generation of spec file as dependency for package task
Rake.application.lookup(:package).prerequisites << "generate_spec"
