#!/usr/bin/env ruby
#--
# Gloves Users Library
#
# Copyright (C) 2011 Novell, Inc.
#   This library is free software; you can redistribute it and/or modify
# it only under the terms of version 2.1 or version 3 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
#   You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#++

$LOAD_PATH.unshift File.join(File.dirname(__FILE__),"..","lib")
require "glove/users"
require "dbus_clients/backend_exception"
begin
  args = {}

  unless ARGV[0].nil?
    if ARGV[0] == "add" && !ARGV[1].nil?
      args = {
          "username"    => ARGV[1],
          "password"    => ARGV[2] || "q",
          "uid"         => ARGV[3], # with nil, free UID should be used
          "comment"     => ARGV[4],
          "shell"       => "/bin/csh",
          "gid"         => "users"
      }
    end
  end

  unless args.empty?
    ret = Glove::Users::add({}, args)
    puts ret.inspect unless ret.nil?
    if ret.nil?
      error	= Glove::Users::last_error
      puts "returned error: #{error}" if error
    end
  end
rescue DbusClients::BackendException => e
  puts e.backend_backtrace
  raise
end
