#!/usr/bin/env ruby
require "kerberos_client"
if ARGV.empty?
  krb = KerberosClient::read({})
  puts krb.inspect
else
  puts KerberosClient::write({"kerberos_client"=>{"default_realm"=>ARGV[0]}})
end
