#!/usr/bin/env ruby
$LOAD_PATH.unshift File.dirname(__FILE__)
require "kerberos_client"
require "dbus_clients/backend_exception"
begin
  if ARGV.empty?
    krb = KerberosClient::read({})
    puts krb.inspect unless krb.nil?
    if krb.nil?
      error	= KerberosClient::last_error
      puts "returned error: #{error}" if error
    end
  else
    puts KerberosClient::write({"kerberos_client"=>{"default_realm"=>ARGV[0]}})
#  puts KerberosClient::write({"kerberos_client"=>{
#    "default_realm"=>ARGV[0],
#    "ssh_support" => true
#  }})
  end
rescue DbusClients::BackendException => e
  puts e.backend_backtrace
  raise
end
