#--
# Gloves Kerberos Client Library
#
# Copyright (C) 2011 Novell, Inc.
#   This library is free software; you can redistribute it and/or modify
# it only under the terms of version 2.1 or version 3 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
#   You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#++

require "rake"
require "rake/testtask"
require "packaging"

desc "install all things on system"
task :install, :prefix, :ruby_path do |t,args|
  args.with_defaults :prefix => '/',:ruby_path => Dir["/usr/lib*/ruby/vendor_ruby/1.*"][0]
  sh "mkdir -p #{args[:prefix]}#{args[:ruby_path]}/"
  sh "cd #{args[:prefix]}#{args[:ruby_path]}/; mkdir -p glove; cd -"
  sh "cp lib/glove/* #{args[:prefix]}#{args[:ruby_path]}/glove"
end

Packaging::Configuration.run do |conf|
  conf.obs_project = "YaST:Head:YaST++"
  conf.obs_target = "devel_languages_ruby_extensions_openSUSE_Factory"
  conf.package_name = "gloves-kerberos-client"
end

Rake::TestTask.new do |t|
  t.test_files = FileList['test/*.rb']
  t.verbose = true
end

task :generate_spec do
  sh "sed 's/VERSION_TEMPLATE/#{Packaging::Configuration.instance.version}/g' gloves-kerberos-client.spec.template > package/gloves-kerberos-client.spec"
end

#add generation of spec file as dependency for package task
Rake.application.lookup(:package).prerequisites << "generate_spec"
