#!/usr/bin/env ruby
#--
# YaST++ Users Library
#
# Copyright (C) 2011 Novell, Inc.
#   This library is free software; you can redistribute it and/or modify
# it only under the terms of version 2.1 or version 3 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
#   You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#++

require 'rubygems'
require '/usr/share/config_agents/services/file/sysconfig' # ?

begin
  args = {}

  if ( !ARGV[0].nil? && File.exist?( "#{ARGV[ 0]}"))
#  if !ARGV[0].nil?
    args = { "file" => "#{ARGV[ 0]}" }
  else
    puts "no file specified or file not found"
    exit
  end

  puts "Src file: " + args.inspect

#  if ARGV.empty? || !args.empty?
    ifcfg = Sysconfig.new.read(args)
    puts ifcfg.inspect unless ifcfg.nil?
    if ifcfg.nil?
      error = "Cannot read the file"
      puts "returned error: #{error}" if error
    end
#  end
#rescue DbusClients::BackendException => e
#  puts e.backend_backtrace
#  raise
end
