#!/usr/bin/env ruby
#--
# YaST++ Users Library
#
# Copyright (C) 2011 Novell, Inc.
#   This library is free software; you can redistribute it and/or modify
# it only under the terms of version 2.1 or version 3 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
#   You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#++

$LOAD_PATH.unshift File.join(File.dirname(__FILE__),"..","lib")
require "glove/sysconfig"
require "dbus_clients/backend_exception"
begin
  args = {}

  if ( !ARGV[0].nil? && File.exist?( "#{ARGV[ 0]}"))
#  if !ARGV[0].nil?
    args = { "file" => "#{ARGV[ 0]}" }
  else
    puts "no file specified or file not found"
    exit
  end

  puts "Src file: " + args.inspect

    # read
    ifcfg = Glove::Sysconfig::read(args)
    puts "Read values: " + ifcfg.inspect unless ifcfg.nil?
    if ifcfg.nil?
      error = Glove::Sysconfig::last_error
      puts "returned error: #{error}" if error
    end

    # write
    ifcfg[ "WIRELESS_ESSID"] = "\"b'b\"";
    puts "Write values: " + ifcfg.inspect unless ifcfg.nil?

    ret = Glove::Sysconfig::write( args.merge( ifcfg))
    if ret[ "success"] != true
        puts "Write error."
        puts "Desc: " +  ret[ "message"] unless ret[ "message"].nil?;
    end

    # re-read
    ifcfg = Glove::Sysconfig::read(args)
    puts "Current values: " + ifcfg.inspect unless ifcfg.nil?
end
