require "rake"
require "rake/testtask"
require "packaging"

desc "install all things on system"
task :install do
  sh "mkdir -p /etc/dbus-1/system.d/"
  sh "cp -r infrastructure/dbus-policies/* /etc/dbus-1/system.d/"
  sh "mkdir -p /usr/share/dbus-1/system-services/"
  sh "cp -r infrastructure/dbus-services/* /usr/share/dbus-1/system-services/"
  sh "mkdir -p /usr/share/config_agents/"
  sh "cp -r infrastructure/bin services /usr/share/config_agents/"
  sh "cp -r infrastructure/polkit-definitions /usr/share/polkit-1/actions/"
  sh "cd /usr/lib*/ruby/vendor_ruby/1.*/; mkdir -p config_agent; cd -"
  sh "cp -r infrastructure/clients/config_agent /usr/lib*/ruby/vendor_ruby/1.*/"
  sh "chmod +x /usr/share/config_agents/bin/*/*.rb"
  `pkill -f '/usr/share/config_agents/bin/.*/.*\.rb' || true`
end

Rake::TestTask.new do |t|
  t.test_files = FileList['test/*.rb']
  t.verbose = true
end
