#!/usr/bin/env ruby
#--
# YaST++ Keyboard Library
#
# Copyright (C) 2011 Novell, Inc.
#   This library is free software; you can redistribute it and/or modify
# it only under the terms of version 2.1 or version 3 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
#   You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#++

$LOAD_PATH.unshift File.join(File.dirname(__FILE__),"..","lib")
require "y_lib/susefirewall2"
require "dbus_clients/backend_exception"
begin
  args = {}

  if ARGV.empty?
    susefirewall2 = YLib::Susefirewall2::read(args)
    puts susefirewall2.inspect

    if susefirewall2.nil?
      error = YLib::Susefireewall2::last_error
      puts "returned error: #{error}" if error
    end
  else
    puts YLib::Susefirewall2::modify({}, {"susefirewall2"=>ARGV[0]})
  end
rescue DbusClients::BackendException => e
  puts e.backend_backtrace
  raise
end
