#--
# Config Agents Framework
#
# Copyright (C) 2011 Novell, Inc.
#   This library is free software; you can redistribute it and/or modify
# it only under the terms of version 2.1 or version 3 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
#   You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#++

require "rake"
require "rake/testtask"
require "packaging"

desc "install all things on system"
task :install, :prefix, :ruby_path do |t,args|
  args.with_defaults :prefix => '/',:ruby_path => Dir["/usr/lib*/ruby/vendor_ruby/1.*/"][0]
  sh "mkdir -p #{args[:prefix]}usr/share/config_agents/"
  sh "cp -r services #{args[:prefix]}usr/share/config_agents/"
  sh "mkdir -p #{args[:prefix]}usr/share/polkit-1/actions/"
  sh "cp infrastructure/polkit-definitions/* #{args[:prefix]}usr/share/polkit-1/actions/ || true"
  sh "mkdir -p #{args[:prefix]}#{args[:ruby_path]}/"
  sh "cd #{args[:prefix]}#{args[:ruby_path]}/; mkdir -p {config_agent,lib}; cd -"
  sh "cp -r infrastructure/clients/config_agent #{args[:prefix]}usr/lib*/ruby/vendor_ruby/1.*/"
  
  ruid=%x( stat -c %u `tty` | tr -d '\n' )   # id -ur doesn't work in Linux
  sh "cd ext; sudo -u\##{ruid} ruby extconf.rb --with-glib-include=/usr/include/glib-2.0 && sudo -u\##{ruid} make all; cd -"
  sh "cp -r ext/*.so #{args[:prefix]}usr/lib*/ruby/vendor_ruby/1.*/lib/"
end

Rake::TestTask.new do |t|
  t.test_files = FileList['test/*.rb']
  t.verbose = true
end


task :generate_spec do
  sh "sed 's/VERSION_TEMPLATE/#{Packaging::Configuration.instance.version}/g' config_agent-sysconfig.spec.template > package/config_agent-sysconfig.spec"
end

#add generation of spec file as dependency for package task
Rake.application.lookup(:package).prerequisites << "generate_spec"
